import { VocabularyManager } from './vocabularyManager';

export class DataLoader {
    constructor() {
        this.vocabularyManager = null;
        this.vocabData = [];
    }

    async loadFromJSON() {
        try {
            // Load the parsed cards JSON that was generated by the parser
            const response = await fetch('/parsed-cards.json');
            if (!response.ok) {
                throw new Error(
                    `Failed to load parsed-cards.json: ${response.status}`
                );
            }

            const parsedCards = await response.json();

            // Create vocabulary manager with the parsed cards
            this.vocabularyManager = new VocabularyManager(parsedCards);

            // Convert to simple vocabData format for the table
            this.vocabData = parsedCards
                .map((card) => {
                    const { location } = card;
                    const listNum =
                        location?.vocabulary === 'I'
                            ? 1
                            : location?.vocabulary === 'II'
                            ? 2
                            : location?.vocabulary === 'III'
                            ? 3
                            : location?.vocabulary === 'IV'
                            ? 4
                            : location?.vocabulary === 'V'
                            ? 5
                            : location?.vocabulary === 'VI'
                            ? 6
                            : location?.vocabulary === 'VII'
                            ? 7
                            : location?.vocabulary === 'VIII'
                            ? 8
                            : location?.vocabulary === 'IX'
                            ? 9
                            : location?.vocabulary === 'X'
                            ? 10
                            : 0;

                    return {
                        id: `${
                            location?.book?.toString().padStart(2, '0') || '00'
                        }-${
                            location?.lesson?.toString().padStart(2, '0') ||
                            '00'
                        }-${listNum.toString().padStart(2, '0')}-${
                            location?.order?.toString().padStart(2, '0') || '00'
                        }`,
                        book: location?.book || 0,
                        lesson: location?.lesson || 0,
                        list: listNum,
                        hanzi: card.simplified,
                        pinyin: card.pinyin,
                        pos: card.partOfSpeech || '',
                        translation: card.meaning || '',
                        traditional: card.traditional,
                        guid: card.guid,
                        tags: card.tags,
                        variants: card.variants,
                        // Keep the full location for reference
                        location: card.location,
                    };
                })
                .sort((a, b) => {
                    // Sort by book, lesson, list, order
                    if (a.book !== b.book) return a.book - b.book;
                    if (a.lesson !== b.lesson) return a.lesson - b.lesson;
                    if (a.list !== b.list) return a.list - b.list;
                    return a.id.split('-')[3] - b.id.split('-')[3];
                });

            return { success: true };
        } catch (error) {
            console.error('Failed to load data from JSON:', error);
            return { success: false, error: error.message };
        }
    }

    getVocabData() {
        return this.vocabData;
    }

    getVocabularyManager() {
        return this.vocabularyManager;
    }

    // Add this helper method to get stats
    getStats() {
        if (!this.vocabularyManager) return null;
        return this.vocabularyManager.getStatistics();
    }
}

// Singleton instance
let instance = null;

export function getDataLoader() {
    if (!instance) {
        instance = new DataLoader();
    }
    return instance;
}
