export const vocabData = [
  { id: 1, hanzi: "週末", pinyin: "zhōumò", pos: "(N)", translation: "weekend" },
  { id: 2, hanzi: "聽", pinyin: "tīng", pos: "(V)", translation: "to listen" },
  { id: 3, hanzi: "音樂", pinyin: "yīnyuè", pos: "(N)", translation: "music" },
  { id: 4, hanzi: "運動", pinyin: "yùndòng", pos: "(Vi)", translation: "to exercise" },
  { id: 5, hanzi: "打", pinyin: "dǎ", pos: "(V)", translation: "to play (ball games)" },
  { id: 6, hanzi: "網球", pinyin: "wǎngqiú", pos: "(N)", translation: "tennis" },
  { id: 7, hanzi: "棒球", pinyin: "bàngqiú", pos: "(N)", translation: "baseball" },
  { id: 8, hanzi: "和", pinyin: "hàn", pos: "(Conj)", translation: "and, as well as" },
  { id: 9, hanzi: "游泳", pinyin: "yóuyǒng", pos: "(V-sep)", translation: "to swim" },
  { id: 10, hanzi: "常", pinyin: "cháng", pos: "(Adv)", translation: "often" },
  { id: 11, hanzi: "籃球", pinyin: "lánqiú", pos: "(N)", translation: "basketball" },
  { id: 12, hanzi: "也", pinyin: "yě", pos: "(Adv)", translation: "also" },
  { id: 13, hanzi: "踢", pinyin: "tī", pos: "(V)", translation: "to kick" },
  { id: 14, hanzi: "足球", pinyin: "zúqiú", pos: "(N)", translation: "soccer" },
  { id: 15, hanzi: "覺得", pinyin: "juéde", pos: "(Vst)", translation: "to feel, to think" },
  { id: 16, hanzi: "好玩", pinyin: "hǎowán", pos: "(Vs)", translation: "interesting, fun" },
  { id: 17, hanzi: "明天", pinyin: "míngtiān", pos: "(N)", translation: "tomorrow" },
  { id: 18, hanzi: "早上", pinyin: "zǎoshàng", pos: "(N)", translation: "morning" },
  { id: 19, hanzi: "去", pinyin: "qù", pos: "(V)", translation: "to go" },
  { id: 20, hanzi: "怎麼樣", pinyin: "zěnmeyàng", pos: "(Vs)", translation: "How about it?" },
  { id: 21, hanzi: "啊", pinyin: "a", pos: "(Ptc)", translation: "particle" },
  { id: 22, hanzi: "白如玉", pinyin: "Bái Rúyù", pos: "Name", translation: "a woman from the US" },
  { id: 23, hanzi: "今天", pinyin: "jīntiān", pos: "(N)", translation: "today" },
  { id: 24, hanzi: "晚上", pinyin: "wǎnshàng", pos: "(N)", translation: "evening" },
  { id: 25, hanzi: "看", pinyin: "kàn", pos: "(V)", translation: "to watch" },
  { id: 26, hanzi: "電影", pinyin: "diànyǐng", pos: "(N)", translation: "movie" },
  { id: 27, hanzi: "妳", pinyin: "nǐ", pos: "(N)", translation: "you (female)" },
  { id: 28, hanzi: "想", pinyin: "xiǎng", pos: "(Vaux)", translation: "to want" },
  { id: 29, hanzi: "還是", pinyin: "háishì", pos: "(Conj)", translation: "or" },
  { id: 30, hanzi: "吧", pinyin: "ba", pos: "(Ptc)", translation: "suggestion particle" },
  { id: 31, hanzi: "可以", pinyin: "kěyǐ", pos: "(Vaux)", translation: "could/can" },
  { id: 32, hanzi: "學", pinyin: "xué", pos: "(V)", translation: "to learn" },
  { id: 33, hanzi: "中文", pinyin: "Zhōngwén", pos: "(N)", translation: "Chinese language" },
  { id: 34, hanzi: "一起", pinyin: "yìqǐ", pos: "(Adv)", translation: "together" },
  { id: 35, hanzi: "吃", pinyin: "chī", pos: "(V)", translation: "to eat" },
  { id: 36, hanzi: "晚飯", pinyin: "wǎnfàn", pos: "(N)", translation: "dinner" },
  { id: 37, hanzi: "菜", pinyin: "cài", pos: "(N)", translation: "cuisine" },
  { id: 38, hanzi: "越南", pinyin: "Yuènán", pos: "Name", translation: "Vietnam" },
  { id: 39, hanzi: "做什麼", pinyin: "zuò shénme", pos: "Phrase", translation: "do what" },
  { id: 40, hanzi: "好啊", pinyin: "hǎo a", pos: "Phrase", translation: "OK" },
  { id: 41, hanzi: "好不好", pinyin: "hǎo bù hǎo", pos: "Phrase", translation: "How about...?" }
];